
import 'package:get/get.dart';

class Translate extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'english':{
      'Customer':'Customer',
      'Octoboss':'Octoboss',
      'Email':'Email',
      'Chat':'Chat',
      'Name':'Name',
      'Select Issue':'Select Issue',
      'Password':'Password',
      'Full Address':'Full Address',
      'City':'City',
      'Street Number' : 'Street Number',
      'Please purchase membership to become active':'Please purchase membership to become active',
      'Street Name':'Street Name',
      'Unit Number':'Unit Number',
      'Job Title' :'Job Title',
      'Job Info':'Job Info',
      'Detailed Description':'Detailed Description',
      'Country Code':'Country Code',
      'Select Language':'Select Language',
      'Forget password?':'Forget password?',
      'Sign in':'Sign in',
      'I don’t have an account':'I don’t have an account',
      'Create a customer account':'Create a customer account',
      'Create a Octoboss Account':'Create a Octoboss Account',
      'First Name':'First Name',
      'Last Name':'Last Name',
      'Email Address':'Email Address',
      'Phone Number':'Phone Number',
      'Date of Birth':'Date of Birth',
      'Street Address':'Street Address',
      'Postal Code':'Postal Code',
      'Agree with':'Agree with',
      'Terms & Condition':'Terms & Condition',
      'Already have account?':'Already have account?',
      'Create':'Create',
      'Home':'Home',
      'Issues':'Issues',
      'Favorite':'Favorite',
      'Chats':'Chats',
      'Settings':'Settings',
      'Profile':'Profile',
      'Language':'Language',
      'Languages':'Languages',
      'English':'English',
      'French':'French',
      'Arabic':'Arabic',
      'Terms and conditions':'Terms and conditions',
      'About us':'About us',
      'Logout':'Logout',
      'Save':'Save',
      'Messages':'Messages',
      'Make an offer':'Make an offer',
      'Time':'Time',
      'Date':'Date',
      'Choose issue':'Choose issue',
      'Price':'Price',
      'Duration':'Duration',
      'Send offer':'Send offer',
      'No recents':'No recents',
      'Write something':'Write something',
      'Document':'Document',
      'Camera':'Camera',
      'Gallery':'Gallery',
      'Audio':'Audio',
      'Contact':'Contact',
      'Share issue':'Share issue',
      'Favorites':'Favorites',
      'Pending':'Pending',
      'Processing':'Processing',
      'Done':'Done',
      'Public issue':'Public issue',
      'Add new issue':'Add new issue',
      'Location':'Location',
      'Description':'Description',
      'Tags':'Tags',
      'Status':'Status',
      'Enter tags separated by comma ( , )':'Enter tags separated by (,)',
      'Choose problem':'Choose problem',
      'Please choose a language':'Please choose a language',
      'Choose image':'Choose image',
      'Annoucement':'Annoucement',
      'Cancel':'Cancel',
      'On':'On',
      'Off':'Off',
      'Electricity':'Electricity',
      'Phone':'Phone',
      'Elevator':'Elevator',
      'Carpenter':'Carpenter',
      'Painting':'Painting',
      'Network':'Network',
      'Plumbing':'Plumbing',
      'A/C':'A/C',
      'Mowing':'Mowing',
      'Search any Services':'Search any Services',
      'Result offering Benefits':'Result offering Benefits',
      'Featured':'Featured',
      'Octoboss Profile':'Octoboss Profile',
      'Services Offered':'Services Offered',
      'Country':'Country',
      'Chat with me':'Chat with me',
      'Certificates':'Certificates',
      'Work Pictures':'Work Pictures',
      'Rating & Reviews':'Rating & Reviews',
      'Close':'Close',
      'Complete Now':'Complete Now',
      'Do it later':'Do it later',
      'Membership':'Membership',
      'Job':'Job',
      'jobs':'jobs',
      'Report':'Report',
      'Public':'Public',
      'Boost':'Boost',
      'InActive':'InActive',
      'Active':'Active',
      'Silver':'Silver',
      'Diamond':'Diamond',
      'Basic':'Basic',
      'Basic':'Basic',
      'On date':'On date',
      'Search by Language':'Search by Language',
      'Search by Tags':'Search by Tags',
      'Issues Market':'Issues Market',
      'Issue Details':'Issue Details',
      'Problem':'Problem',
      'Complete your profile':'Complete your profile',
      'Choose Services':'Choose Services',
      'Others':'Others',
      'Switch user':'Switch user',
      'Service Name':'Service Name',
      'Add Service':'Add Service',
      'Rating':'Rating',
      'Total hours':'Total hours',
      'Total revenue':'Total revenue',
      'Done jobs':'Done jobs',
      'Reports':'Reports',
      'Add work pictures':'Add work pictures',
      'Add Certificates':'Add Certificates',
      'Please select services':'Please select services',
      'Search Name':'Search Name',
    },
    'french':{
      'Customer':'Client',
      'Octoboss':'Octoboss',
      'Email':'Courriel',
      'Full Address':'Adresse complète',
      'City':'Ville',
      'Name':'Nom',
      'Chat':'Discuter',
      'Select Issue':'Sélectionnez le problème',
      'Please purchase membership to become active':'Veuillez acheter un abonnement pour devenir actif',
      'Street Name':'Nom de rue',
      'Street Number' : 'numéro de rue',
      'Unit Number':"Numéro d'unité",
      'Job Title' :"Titre d'emploi",
      'Job Info':"Informations sur l'emploi",
      'Detailed Description':'Description détaillée',
      'Select Language':'Choisir la langue',
      'Country Code':'Code postal',
      'Password':'Mot de passe',
      'Forget password?':"J'ai oublié mon mot de passe.",
      'Sign in':'Connexion',
      'I don’t have an account':"Je n'ai pas de compte",
      'Create a customer account':"Créer un compte client",
      'Create a Octoboss Account':"Créer un compte Octoboss",
      'First Name':'Prénom',
      'Last Name':'Nom de famille',
      'Email Address':'Adresse e-mail',
      'Phone Number':"Numéro de téléphone",
      'Date of Birth':'Date de naissance',
      'Street Address':'Adresse',
      'Postal Code':'Code postal',
      'Agree with':'Accepter les',
      'Terms & Condition':'Termes et conditions',
      'Already have account?':'Vous avez déjà un compte ?',
      'Create':'Créer',
      'Home':'Accueil',
      'Issues':'Problèmes',
      'Favorite':'Favoris',
      'Chats':'Messages',
      'Settings':'Configuration',
      'Profile':'Profil',
      'Language':'Langue',
      'Languages':'langues',
      'English':'Anglais',
      'French':'Français',
      'Arabic':'Arabe',
      'Terms and conditions':'Termes et conditions',
      'About us':'A propos de nous',
      'Logout':'Déconnexion',
      'Save':'Sauvegarder',
      'Messages':'Messages',
      'Make an offer':'Faire une offre',
      'Time':'Heure',
      'Date':'Date',
      'Choose issue':"Choisir l'enjeu",
      'Price':'Prix',
      'Duration':'Durée',
      'Send offer':"Envoyer l'offre",
      'No recents':'Pas de récents',
      'Write something':'Écrivez votre commentaire',
      'Document':'Document',
      'Camera':'Caméra',
      'Gallery':'Galerie',
      'Audio':'Audio',
      'Contact':'Contactez',
      'Share issue':'Partager votre problème',
      'Favorites':'Favoris',
      'Pending':'En attente',
      'Processing':'En cours de traitement',
      'Done':'Terminé',
      'Public issue':'Question publique',
      'Add new issue':'Ajouter une nouvelle question',
      'Location':'Coordonnées',
      'Description':'Description',
      'Tags':'Mots-clés',
      'Status':'État',
      'Enter tags separated by comma ( , )':'Entrez les Mots-clés séparées par ( , )',
      'Choose problem':'Choisir le problème',
      'Please choose a language':'Veuillez choisir une langue',
      'Choose image':'Choisissez une image',
      'Annoucement':'Annonce',
      'Cancel':'Annuler',
      'On':'Activé',
      'Off':'Désactivé',
      'Electricity':'Électricité',
      'Phone':'Téléphone',
      'Elevator':'Ascenseur',
      'Carpenter':'Charpentier',
      'Painting':'Peinture',
      'Network':'Réseau',
      'Plumbing':'Plomberie',
      'A/C':'climatisation',
      'Mowing':'Tonte de gazon',
      'Search any Services':'Rechercher tout type de services',
      'Result offering Benefits':'Résultat',
      'Featured':'En vedette',
      'Octoboss Profile':"Profil d'Octoboss",
      'Services Offered':'Services offerts',
      'Country':'Pays',
      'Chat with me':'Communiquer avec moi',
      'Certificates':'Certificats',
      'Work Pictures':'Images de travaux',
      'Rating & Reviews':'Évaluation et commentaires',
      'Close':'Fermer',
      'Complete Now':'Compléter maintenant',
      'Do it later':'Faites-le plus tard',
      'Membership':'Abonnement',
      'Job':'Emploi',
      'jobs':'Emplois',
      'Report':'Rapport',
      'Public':'Public',
      'Boost':'Booster',
      'InActive':'inactif',
      'Active':'Actif',
      'Silver':'Argent',
      'Diamond':'Diamant',
      'Basic':'De base',
      'On date':'Sur les données',
      'Search by Language':'Recherche par langue',
      'Search by Tags':'Recherche par Mots-clés',
      'Issues Market':'tous les problèmes',
      'Issue Details':'Détails du problème',
      'Problem':'Problème',
      'Complete your profile':'Complétez votre profil',
      'Choose Services':'Choisir les services',
      'Others':'Autres',
      'Switch user':"Changer d'utilisateur",
      'Service Name':'Nom du service',
      'Add Service':'Ajouter un service',
      'Rating':'Évaluation',
      'Total hours':'Nombre total des heures',
      'Total revenue':'Revenu total',
      'Done jobs':'Travaux effectués',
      'Reports':'Rapports',
      'Add work pictures':'Ajouter des images du travail',
      'Add Certificates':'Ajouter des certificats',
      'Please select services':'Veuillez sélectionner les services',
      'Search Name':'Recherche par nom',
    },
    'arabic':{
      'Customer':'عميل',
      'Octoboss':'اكتوبوس',
      'Email':'بريد الكتروني',
      'Full Address':'العنوان الكامل',
      'City':'مدينة',
      'Name':'اسم',
      'Chat':'دردشة',
      'Select Issue':'حدد المشكلة',
      'Street Name':'اسم الشارع',
      'Street Number' : 'رقم الشارع',
      'Unit Number':'رقم الوحدة',
      'Job Title' :'مسمى وظيفي',
      'Job Info':'معلومات الوظيفة',
      'Detailed Description':'وصف مفصل',
      'Please purchase membership to become active':'الرجاء شراء العضوية لتصبح نشطة',
      'Select Language':'اختار اللغة',
      'Country Code':'الرقم الدولي',
      'Password':'الرقم السري',
      'Forget password?':"نسيت كلمة المرور",
      'Sign in':'الدخول',
      'I don’t have an account':"غير مسجل",
      'Create a customer account':"انشاء حساب عميل جديد",
      'Create a Octoboss Account':"انشاء حساب اكتوبوس جديد",
      'First Name':'الاسم الاول',
      'Last Name':'اسم العائلة',
      'Email Address':'البريد الالكتروني',
      'Phone Number':"رقم الهاتف",
      'Date of Birth':'تاريخ الميلاد',
      'Street Address':'عناون الشارع',
      'Postal Code':'الرمز البريدي',
      'Agree with':'اوافق',
      'Terms & Condition':'الشروط والاحكام',
      'Already have account?':'لديك حساب؟',
      'Create':'انشاء',
      'Home':'الصفحة الرئيسية',
      'Issues':'طلبات',
      'Favorite':'المفضلة',
      'Chats':'الدردشة',
      'Settings':'الاعدادات',
      'Profile':'الملف التعريفي',
      'Language':'اللغة',
      'Languages':'اللغات',
      'English':'الانجليزية',
      'French':'الفرنسية',
      'Arabic':'العربية',
      'Terms and conditions':'الشروط والاحكام',
      'About us':'من نحن',
      'Logout':'تسجيل الخروج',
      'Save':'حفظ',
      'Messages':'الرسائل',
      'Make an offer':'قدم عرض',
      'Time':'الوقت',
      'Date':'التاريخ',
      'Choose issue':"اختر طلب",
      'Price':'المبلغ',
      'Duration':'المدة',
      'Send offer':"ارسال العرض",
      'No recents':'لا يوجد ملفات حديثة',
      'Write something':'اكتب شيئا',
      'Document':'الوثيقة',
      'Camera':'الكاميرا',
      'Gallery':'الالبوم',
      'Audio':'الصوتيات',
      'Contact':'اتصل بنا',
      'Share issue':'شارك الطلب',
      'Favorites':'المفضلة',
      'Pending':'قيد المعالجة',
      'Processing':'قيد الاجراء',
      'Done':'منتهية',
      'Public issue':'طلبات عامة',
      'Add new issue':'اضافة طلب جديد',
      'Location':'الموقع',
      'Description':'الوصف',
      'Tags':'كلمات بحث',
      'Status':'الحالة',
      'Enter tags separated by comma ( , )':'ادخل كلمات بحثية مفصولة بفاصلة',
      'Choose problem':'اختر طلب',
      'Please choose a language':'اختر اللغة',
      'Choose image':'اختر صورة',
      'Annoucement':'الاعلانات',
      'Cancel':'الغاء',
      'On':'تشغيل',
      'Off':'اقفال',
      'Electricity':'الكهرباء',
      'Phone':'الجوال',
      'Elevator':'المصعد',
      'Carpenter':'النجارة',
      'Painting':'الدهانات',
      'Network':'الشبكات',
      'Plumbing':'السباكة',
      'A/C':'التكييف',
      'Mowing':'قص العشب',
      'Search any Services':'البحث بالخدمة',
      'Result offering Benefits':'النتائج',
      'Featured':'متميز',
      'Octoboss Profile':"ملف الاكتوبوس الشخصي",
      'Services Offered':'الخدمات المقدمة',
      'Country':'الدولة',
      'Chat with me':'تحدث معي',
      'Certificates':'الشهادات',
      'Work Pictures':'صور لبعض الاعمال',
      'Rating & Reviews':'التقييم والتعليقات',
      'Close':'اغلاق',
      'Complete Now':'اكمال الان',
      'Do it later':'اكمال لاحقا',
      'Membership':'العضوية',
      'Job':'العمل',
      'jobs':'الاعمال',
      'Report':'التقرير',
      'Public':'عام',
      'Boost':'انتشر بشكل اسرع',
      'InActive':'غير فعال',
      'Active':'فعال',
      'Silver':'الفضي',
      'Diamond':'الالماسي',
      'Basic':'المبدئي',
      'On date':'المبدئي',
      'Search by Language':'البحث باللغة',
      'Search by Tags':'البحث بالكلمات المفتاحية',
      'Issues Market':'سوق الطلبات',
      'Issue Details':'تفاصيل الطلب',
      'Problem':'الطلب',
      'Complete your profile':'اكمل ملفك الشخصي ',
      'Choose Services':'اختر الخدمات',
      'Others':'اخرى',
      'Switch user':"تغيير المستخدم",
      'Service Name':'اسم الخدمة',
      'Add Service':'اضف خدمة',
      'Rating':'التقييم',
      'Total hours':'عدد الساعات الاجمالي',
      'Total revenue':'الدخل الاجمالي',
      'Done jobs':'الاعمال التي تم الانتهاء منها',
      'Reports':'التقارير',
      'Add work pictures':'اضف صور الاعمال',
      'Add Certificates':'اضف الشهادات',
      'Please select services':'اختر الخدمات',
      'Search Name':'ابحث بالاسم',
    },
  };
}
